# Set theme
theme: alembic-jekyll-theme

# Gems
gems:
- jekyll-email-protect

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://wwww.stelro.nl'
baseurl: ''
title: 'Huwelijk Stella de Man & Rob Schoonman'
description: 'Huwelijkswebsite voor Stella de Man en Rob Schoonman'
permalink: pretty
email: jules.schoonman@gmail.com

# Pagination

# Header nav

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
